# Generated by Django 3.2 on 2024-02-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_title_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='author',
        ),
    ]
