# Generated by Django 3.2 on 2024-02-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_title_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='score',
        ),
    ]
