# Generated by Django 3.2 on 2024-02-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_rating_review_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created',
            new_name='pub_date',
        ),
    ]
