# Generated by Django 3.2 on 2024-02-18 01:04

from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Обязательное. Символов <= 150', max_length=150, unique=True, validators=[users.validators.MyUnicodeUsernameValidator(), users.validators.validate_username], verbose_name='username'),
        ),
    ]
