# Generated by Django 3.2 on 2024-02-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='asd', max_length=255, verbose_name='Код подтверждения'),
            preserve_default=False,
        ),
    ]
