# Generated by Django 3.2 on 2024-02-19 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Значение не может быть меньше {value}'), django.core.validators.MaxValueValidator(10, message='Значение не может быть больше {value}')], verbose_name='Рейтинг'),
        ),
    ]
