# Generated by Django 3.2 on 2024-02-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='Имя жанра'),
        ),
    ]
