# Generated by Django 3.2 on 2024-02-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default=None, max_length=256, verbose_name='Имя жанра'),
        ),
    ]
